kind = "mobile"
previewPath = "/"
title = "Trampaí"
version = "1.0.0"
id = "artifacts/trampai"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
name = "expo"
paths = [ "/" ]
localPort = 18717
ensurePreviewReachable = "/status"

[services.development]
run = "pnpm --filter @workspace/trampai run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/trampai", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/trampai", "run", "serve" ]

[services.env]
PORT = "18717"
BASE_PATH = "/"
